# Use the official Nginx image as the base
FROM nginx:1-alpine

# Copy the custom Nginx configuration file into the image
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose the default Nginx port
EXPOSE 443

# Command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
