name: Deploy Test Production Environment 2

on:
  push:
    branches:
      - 'prod-test-env-2'
  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
    
jobs:
  build-and-transfer:
    name: Build docker image and transfer to remote server
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build the application Docker image
    - name: Build custom App Docker image
      working-directory: code
      run: |
        docker buildx build --platform linux/amd64 -t mpi-employment-interest-tool:latest --load .

    # Build the custom Nginx Docker image
    - name: Build custom Nginx Docker image
      working-directory: code
      run: |
        docker buildx build --platform linux/amd64 -f Dockerfile.nginx -t custom-nginx:latest --load .

    - name: Save application Docker image to tar file
      working-directory: code
      run: |
        docker save mpi-employment-interest-tool:latest -o mpi-employment-interest-tool.tar

    - name: Save custom Nginx Docker image to tar file
      working-directory: code
      run: |
        docker save custom-nginx:latest -o custom-nginx.tar

    - name: Save SSH private key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY_VALUE }}" > ${{ secrets.SSH_PRIVATE_KEY_FILENAME }}
        chmod 600 ${{ secrets.SSH_PRIVATE_KEY_FILENAME }}

    - name: Install cloudflared
      run: |
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
        chmod +x cloudflared
        sudo mv cloudflared /usr/local/bin/

    - name: Transfer Docker images to VM
      run: |
        scp -o StrictHostKeyChecking=no \
            -o ProxyCommand="cloudflared access ssh --hostname %h --service-token-id ${{ secrets.SERVICE_TOKEN_ID }} --service-token-secret ${{ secrets.SERVICE_TOKEN_SECRET }}" \
            -i ${{ secrets.SSH_PRIVATE_KEY_FILENAME }} \
            code/mpi-employment-interest-tool.tar \
            code/custom-nginx.tar \
            mpi@mpissh.stijnrombouts.be:~/
